# Generated by Django 5.1.4 on 2025-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
